# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Elm site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install elm-land and node packages
        run: |
          npm install
      - name: build
        run: |
          npx tailwindcss -i ./src/input.css -o ./static/main.css --minify
          npx elm-land build

      - name: change path in index.html
        run: sed -i -e 's|href="/main.css"|href="/intervirt/main.css"|' -e 's|src="/assets/\(.*\).js"|src="/intervirt/assets/\1.js"|' ./dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/dist/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
